# Generated by Django 6.0.3 on 2026-03-28 10:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('developer', 'Developer'), ('manager', 'Manager'), ('student', 'Student'), ('designer', 'Designer')], max_length=20)),
                ('persona_description', models.TextField()),
                ('notification_pref', models.CharField(choices=[('all', 'All'), ('priority', 'Priority'), ('urgent_only', 'Urgent Only')], default='all', max_length=20)),
                ('telegram_chat_id', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('block_type', models.CharField(choices=[('meeting', 'Meeting'), ('focus', 'Focus'), ('break', 'Break'), ('free', 'Free')], max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_blocks', to='notifications.user')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_app', models.CharField(choices=[('slack', 'Slack'), ('gmail', 'Gmail'), ('github', 'GitHub'), ('calendar', 'Calendar'), ('youtube', 'YouTube')], max_length=20)),
                ('message', models.TextField()),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('ai_priority', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='', max_length=10)),
                ('ai_category', models.CharField(blank=True, choices=[('social', 'Social'), ('work', 'Work'), ('urgent', 'Urgent')], default='', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notifications.user')),
            ],
        ),
        migrations.CreateModel(
            name='DecisionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active_app_snapshot', models.CharField(blank=True, max_length=100)),
                ('active_app_category_snapshot', models.CharField(blank=True, max_length=20)),
                ('schedule_block_snapshot', models.CharField(blank=True, max_length=20)),
                ('recent_ignored_count', models.IntegerField(default=0)),
                ('last_interactions_snapshot', models.JSONField(default=list)),
                ('time_of_day_snapshot', models.CharField(blank=True, max_length=20)),
                ('inferred_mode', models.CharField(choices=[('focus', 'Focus'), ('work', 'Work'), ('meeting', 'Meeting'), ('relax', 'Relax'), ('sleep', 'Sleep')], max_length=20)),
                ('decision', models.CharField(choices=[('send', 'Send'), ('delay', 'Delay'), ('block', 'Block')], max_length=10)),
                ('ai_reason', models.TextField(blank=True)),
                ('delay_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='notifications.notificationevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_logs', to='notifications.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_name', models.CharField(max_length=100)),
                ('app_category', models.CharField(choices=[('productivity', 'Productivity'), ('communication', 'Communication'), ('leisure', 'Leisure')], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_sessions', to='notifications.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserInteractionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('seen', 'Seen'), ('ignored', 'Ignored'), ('dismissed', 'Dismissed'), ('snoozed', 'Snoozed')], max_length=20)),
                ('actioned_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='notifications.notificationevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_logs', to='notifications.user')),
            ],
        ),
    ]
