# Generated by Django 6.0.3 on 2026-03-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationevent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('blocked', 'Blocked'), ('queued', 'Queued'), ('delivered', 'Delivered')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='manual_mode',
            field=models.CharField(choices=[('auto', 'Auto'), ('focus', 'Focus'), ('work', 'Work'), ('meeting', 'Meeting'), ('relax', 'Relax'), ('sleep', 'Sleep')], default='auto', max_length=10),
        ),
    ]
